"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import "../structured.css";
import { ProjectPageHeader, useActiveProject } from "@/components/project-ui";

type Source = { id: string; name: string; type: string; status: string; chunkCount: number; lastIndexedAt: string | null };

export default function SourcesPage() {
  const project = useActiveProject();
  const [sources, setSources] = useState<Source[]>([]); const [message, setMessage] = useState(""); const [noteTitle, setNoteTitle] = useState(""); const [note, setNote] = useState(""); const [githubUrl, setGithubUrl] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  async function refresh() { const response = await fetch(`/api/v1/projects/${encodeURIComponent(project.id)}/sources`); if (response.ok) setSources((await response.json()).sources || []); }
  useEffect(() => { void refresh(); }, [project.id]);
  async function upload(form: FormData) { const response = await fetch(`/api/v1/projects/${encodeURIComponent(project.id)}/sources`, { method: "POST", body: form }); const data = await response.json(); if (!response.ok) { setMessage(data.error?.message || "Could not index this source."); return false; } setMessage(`${data.source.name} was added to ${project.name}.`); await refresh(); return true; }
  async function chooseFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append("file", file); await upload(form); event.target.value = ""; }
  async function addNote(event: FormEvent) { event.preventDefault(); if (!note.trim()) return; const form = new FormData(); form.append("name", noteTitle.trim() || "Team note"); form.append("note", note); if (await upload(form)) { setNoteTitle(""); setNote(""); } }
  async function addGitHub(event: FormEvent) { event.preventDefault(); if (!githubUrl.trim()) return; const form = new FormData(); form.append("githubUrl", githubUrl.trim()); if (await upload(form)) setGithubUrl(""); }
  return <main className="structured-page"><ProjectPageHeader /><section className="structured-shell source-shell"><div className="structured-eyebrow">PROJECT SOURCES</div><h1>Give {project.name} useful memory.</h1><p>Files, notes, and public repositories become shared context for your teammates and AI tools.</p><div className="source-actions"><button onClick={() => fileInput.current?.click()}>Upload a document</button><a href="/brief">Edit shared brief</a></div>{message && <div className="source-notice" role="status">{message}</div>}<section className="source-upload-card"><div><h2>Import a public GitHub repository</h2><p>Index its README and important Markdown planning or design files.</p></div><form onSubmit={addGitHub}><input value={githubUrl} onChange={(event) => setGithubUrl(event.target.value)} placeholder="https://github.com/owner/repository" required /><button type="submit">Import repository</button></form></section><section className="source-upload-card"><div><h2>Add a team note</h2><p>Capture a decision, plan, or handoff directly into shared memory.</p></div><form onSubmit={addNote}><input value={noteTitle} onChange={(event) => setNoteTitle(event.target.value)} placeholder="Title, e.g. API rollout plan" /><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Write the note your whole team and agents should remember…" required /><button type="submit">Save to project memory</button></form></section><section className="source-library"><div className="settings-card-heading"><div><h2>Indexed sources</h2><span>{sources.length} sources available to {project.name}.</span></div></div>{sources.length ? sources.map((source) => <article className="source-library-row" key={source.id}><span className="source-library-icon">{source.type === "github" ? "GH" : source.type === "notes" ? "N" : "M"}</span><div><strong>{source.name}</strong><span>{source.type} · {source.chunkCount} memory chunks · {source.lastIndexedAt ? "Indexed" : "Waiting to index"}</span></div><em className={source.status === "indexed" ? "ready" : "pending"}>{source.status}</em></article>) : <div className="source-empty">No sources yet. Upload a Markdown file, import a public GitHub repository, or add a team note above.</div>}</section><input ref={fileInput} type="file" accept=".md,.markdown,.txt" onChange={chooseFile} hidden /></section></main>;
}
