"use client";

import "../structured.css";
import { useEffect, useState } from "react";
import { ProjectPageHeader, useActiveProject } from "@/components/project-ui";

type Settings = { indexGithub: boolean; indexDocuments: boolean; indexNotes: boolean; indexChatExports: boolean };
const items: Array<[keyof Settings, string, string]> = [["indexGithub", "GitHub repositories", "Repository files, commits, and code history"], ["indexDocuments", "Documents", "Markdown, PDF, and project design documents"], ["indexNotes", "Meeting notes", "Pasted notes and planning records"], ["indexChatExports", "AI chat exports", "Previous assistant conversations and decisions"]];

export default function SettingsPage() {
  const project = useActiveProject(); const [settings, setSettings] = useState<Settings>({ indexGithub: true, indexDocuments: true, indexNotes: true, indexChatExports: true }); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/v1/projects/${encodeURIComponent(project.id)}/settings`).then((response) => response.json()).then((data) => data.settings && setSettings(data.settings)); }, [project.id]);
  function toggle(key: keyof Settings) { setSettings((current) => ({ ...current, [key]: !current[key] })); setSaved(false); }
  async function saveSettings() { setSaving(true); const response = await fetch(`/api/v1/projects/${encodeURIComponent(project.id)}/settings`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); setSaving(false); if (response.ok) { setSaved(true); window.setTimeout(() => setSaved(false), 1800); } }
  return <main className="structured-page"><ProjectPageHeader /><section className="structured-shell settings-shell"><div className="structured-eyebrow">PROJECT SETTINGS</div><h1>Choose what becomes memory.</h1><p>Control what OneContext indexes for {project.name}.</p><section className="settings-card"><div className="settings-card-heading"><div><h2>Indexing sources</h2><span>Choose which types of project context are included in memory.</span></div>{saved && <em>Saved</em>}</div>{items.map(([key, title, description]) => <div className="setting-row" key={key}><div><strong>{title}</strong><span>{description}</span></div><button className={`toggle ${settings[key] ? "on" : ""}`} onClick={() => toggle(key)} aria-label={`Toggle ${title}`} aria-pressed={settings[key]}><i /></button></div>)}<div className="settings-save-row"><span>{saved ? "Your preferences are saved." : "Review your choices, then save."}</span><button onClick={saveSettings} disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div></section><section className="settings-card provider-card"><div className="settings-card-heading"><div><h2>AI providers</h2><span>Keys stay in your local environment and are never shown here.</span></div></div><div className="provider-row"><span className="provider-icon">✦</span><div><strong>OpenAI memory services</strong><span>Optional AI retrieval, answers, and memory distillation</span></div><span className="provider-status">Configured locally</span></div><div className="provider-row"><span className="provider-icon">◎</span><div><strong>Gateway extensions</strong><span>ChatGPT, Claude, Codex, and VS Code integration</span></div><span className="provider-status connected">Available</span></div></section></section></main>;
}
